export const Images = {
  // ico
  menu: '/ico/ic-hamburger.svg',
  logo: '/ico/ic-logo.svg',
  circle: '/ico/ic-circle.svg',
  sticker: '/ico/ic-sticker.svg',
  star: '/ico/ic-star.svg',
  starLg: '/ico/ic-star-lg.svg',
  starGreen: '/ico/ic-star-green.svg',
  starSquare: '/ico/ic-star-square.svg',
  starSquarePurple: '/ico/ic-star-square-purple.svg',
  starSquareCoral: '/ico/ic-star-square-coral.svg',
  starAlert: '/ico/ic-star-alert.svg',
  close: '/ico/ic-close.svg',
  maltese: '/ico/ic-maltese.svg',
  flower: '/ico/ic-flower.svg',
  flowerWhite: '/ico/ic-flower-white.svg',
  spark: '/ico/ic-spark.svg',
  dial: '/ico/ic-dial.svg',

  // img
  landing1: '/img/img-landing-1.webp',
  landing2: '/img/img-landing-2.webp',
  bori: '/img/img-bori.webp',
  jjeko: '/img/img-jjeko.webp',
  latte: '/img/img-latte.webp',
  tori: '/img/img-tori.webp',
  ttung: '/img/img-ttung.webp',
  zio: '/img/img-zio.webp',
  home: '/img/img-home.webp',
  park: '/img/img-park.webp',
  walk: '/img/img-walk.webp',

  // img/gallery
  image01: '/img/gallery/img-01.webp',
  image02: '/img/gallery/img-02.webp',
  image03: '/img/gallery/img-03.webp',
  image04: '/img/gallery/img-04.webp',
  image05: '/img/gallery/img-05.webp',
  image06: '/img/gallery/img-06.webp',
  image07: '/img/gallery/img-07.webp',
  image08: '/img/gallery/img-08.webp',
  image09: '/img/gallery/img-09.webp',
  image10: '/img/gallery/img-10.webp',
};
