export const Images = {
  // ico
  menu: '/ico/ic-hamburger.svg',
  logo: '/ico/ic-logo.svg',
  circle: '/ico/ic-circle.svg',
  sticker: '/ico/ic-sticker.svg',
  star: '/ico/ic-star.svg',
  starLg: '/ico/ic-star-lg.svg',
  starGreen: '/ico/ic-star-green.svg',
  starSquare: '/ico/ic-star-square.svg',
  starSquarePurple: '/ico/ic-star-square-purple.svg',
  starSquareCoral: '/ico/ic-star-square-coral.svg',
  starAlert: '/ico/ic-star-alert.svg',
  close: '/ico/ic-close.svg',
  maltese: '/ico/ic-maltese.svg',
  flower: '/ico/ic-flower.svg',
  flowerWhite: '/ico/ic-flower-white.svg',
  spark: '/ico/ic-spark.svg',
  dial: '/ico/ic-dial.svg',

  // img
  landing1: '/img/ic-landing-1.png',
  landing2: '/img/ic-landing-2.png',
  bori: '/img/ic-dog-bori.svg',
  jjeko: '/img/ic-dog-jjeko.svg',
  latte: '/img/ic-dog-latte.svg',
  tori: '/img/ic-dog-tori.svg',
  ttung: '/img/ic-dog-ttung.svg',
  zio: '/img/ic-dog-zio.svg',
  home: '/img/ic-home.png',
  park: '/img/ic-park.png',
  walk: '/img/ic-walk.png',

  // img/gallery
  image01: '/img/gallery/img-01.png',
  image02: '/img/gallery/img-02.png',
  image03: '/img/gallery/img-03.png',
  image04: '/img/gallery/img-04.png',
  image05: '/img/gallery/img-05.png',
  image06: '/img/gallery/img-06.png',
  image07: '/img/gallery/img-07.png',
  image08: '/img/gallery/img-08.png',
  image09: '/img/gallery/img-09.png',
  image10: '/img/gallery/img-10.png',
};
